title: OccupancyReact Final Report
description: A comprehensive analysis of OccupancyNet, a learned neural network controller for autonomous navigation.
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
