title: OccupancyNet Results
description: A comprehensive analysis of OccupancyNet, a learned neural network controller for autonomous navigation.
url: "https://anirudhadg-ati.github.io"
baseurl: "/OccupancyNet-Results"



exclude:
  - README.md

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
